projectName: "Mistral PHP Client"
defaultDoc: "Basics/quick_start.md"
logoUrl: "/images/logo.svg"
logoHref: "https://www.partitech.com/"
projectSource: "https://github.com/partITech/php-mistral"
jumbotronSourceLinkCodeLink: "https://github.com/partITech/php-mistral"
enableSearch: false
jumbotron: true
jumbotronHeader: "Mistral API, Vllm, Ollama, llama.cpp, HuggingFace inference client, Anthropic, Xai"
jumbotronTextLine: "Connect with or without streaming, FIM, function calling, Mixed content, Json format"
jumbotronGetStartedLabel: "Get started"
jumbotronGetStartedLink: "#main-content"
jumbotronSourceLinkCodeLabel: "View on GitHub"
jumbotronCodeLang: "php"
jumbotronCodeContent: |
  $client = new MistralClient(getenv('TOKEN'));
  
  $messages = $client->getMessages()
    ->addSystemMessage(content: 'You are a gentle bot who respond like a pirate')
    ->addUserMessage(content: 'What is the best French cheese?');
  
  foreach ( $client->chat(messages: $messages, params: $params, stream: true) as $chunk ) {
    echo $chunk->getChunk();
  }