services:
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:3.2.1
    command: |
      --model-id mistralai/Ministral-8B-Instruct-2410
    environment:
      - HF_TOKEN=****
      - NVIDIA_VISIBLE_DEVICES=0,1
    volumes:
      - /llm:/llm
      - /Data:/Data
      - /llm/.cache/huggingface/hub:/data/hub
    ports:
      - "40001:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0,1']
              capabilities: [gpu]
    runtime: nvidia
    ipc: host